### ISSUE TITLE
Implement EndTurn reaction class

### ISSUE THREAD

**Issue by kestivvi** [Splendor-Mobile-Game/ServerSide#68]
We need to implement the `EndTurn` reaction for our WebSocket handlers in order to handle player requests to end their turn during a game. This reaction should send a message of type `NEW_TURN_ANNOUNCEMENT` to all players, announcing the end of the current turn and selecting the player for the next turn. It should also include logic to store information about whose turn it is and the order of turns.

Additionally, this reaction should be responsible for detecting when the game ends, which occurs when one player has more than 15 points and the server needs to complete the current turn so that every player has done the same amount of actions.

More info in the java doc of this class.
https://github.com/Splendor-Mobile-Game/ServerSide/blob/7bf308007d5896d58199e58e5a6157ae6235b744/src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/EndTurn.java#L9-L49

**Comment by michalwisniewski3101** [comment]
I implement the EndTurn reaction to handle player requests to end their turn during a game. This reaction send a message to all players, announcing the end of the current turn and selecting the player for the next turn. 

We have to add reaction that should be responsible for detecting when the game ends, which occurs when one player has more than 15 points and the server needs to complete the current turn so that every player has done the same amount of actions.
